info:
  description: Spring Cloud Samples
  url: https://github.com/spring-cloud-samples
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
host.name: localhost
host.poer: 8085
